#!/usr/bin/env python3
"""
Create source_functions.json from path JSON files with function dependency tracking and signatures

This script reads path JSON files from tmp/paths/ directory and creates
a source_functions.json file that includes function dependencies and signatures
extracted from the AST that was already parsed by the preprocessor.

Usage:
    python scripts/create_source_functions_json_with_deps.py <subject_name> <output_dir> <paths_dir> <ast_file>

Example:
    python scripts/create_source_functions_json_with_deps.py bst test/projects/bst tmp/paths tmp/ast/bst.json
"""

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Dict, Set, List, Optional

# Import the signature extraction module
try:
    from extract_function_signatures import extract_all_function_signatures
except ImportError:
    # Try relative import
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from extract_function_signatures import extract_all_function_signatures


class DependencyExtractor:
    """Extract function dependencies from the AST generated by ast_generator.py"""

    def __init__(self, ast_data: Dict):
        self.ast_data = ast_data
        self.functions = {}  # function_name -> function_node
        self.dependencies = {}  # function_name -> set of dependencies

    def extract_dependencies(self) -> Dict[str, List[str]]:
        """
        Extract function dependencies from the AST.
        Returns a dict mapping function_name -> list of required function names.
        """
        root_node = self.ast_data.get('root_node', {})

        # First pass: Find all function definitions
        self._find_all_functions(root_node)

        # Second pass: Analyze dependencies for each function
        for func_name, func_node in self.functions.items():
            deps = set()
            self._find_function_calls(func_node, deps)
            # Remove self-references for non-recursive display (but keep them in the data)
            # Actually, let's keep them as they indicate recursion which is important
            self.dependencies[func_name] = sorted(list(deps))

        return self.dependencies

    def _find_all_functions(self, node: Dict):
        """Recursively find all function definitions in the AST."""
        if node.get('type') == 'function_definition':
            func_name = self._extract_function_name(node)
            if func_name:
                self.functions[func_name] = node

        # Recursively search children
        for child in node.get('children', []):
            self._find_all_functions(child)

    def _extract_function_name(self, func_node: Dict) -> Optional[str]:
        """Extract the function name from a function_definition node."""
        # Navigate through the function definition structure
        for child in func_node.get('children', []):
            name = self._find_identifier_in_declarator(child)
            if name:
                return name
        return None

    def _find_identifier_in_declarator(self, node: Dict) -> Optional[str]:
        """Find the identifier (function name) in a declarator node."""
        if node.get('type') == 'identifier':
            return node.get('text', '')

        # For pointer declarators and function declarators, recurse
        if node.get('type') in ['function_declarator', 'pointer_declarator']:
            for child in node.get('children', []):
                name = self._find_identifier_in_declarator(child)
                if name:
                    return name

        return None

    def _find_function_calls(self, node: Dict, deps: Set[str]):
        """Find all function calls within a function body."""
        if node.get('type') == 'call_expression':
            # Get the function being called
            for child in node.get('children', []):
                if child.get('type') == 'identifier':
                    called_func = child.get('text', '')
                    # Only track calls to user-defined functions (ones we found in the AST)
                    if called_func in self.functions:
                        deps.add(called_func)
                    break

        # Recursively search all children
        for child in node.get('children', []):
            self._find_function_calls(child, deps)


def load_paths_and_merge_dependencies(paths_dir: str, dependencies: Dict[str, List[str]],
                                      signatures: Dict[str, str] = None) -> List[Dict]:
    """
    Load path JSON files and merge with dependency information and signatures.

    Args:
        paths_dir: Directory containing path JSON files
        dependencies: Dict of function_name -> list of required functions
        signatures: Optional dict of function_name -> function signature

    Returns:
        List of source function dictionaries with paths, dependencies, and signatures
    """
    source_functions = []

    if not os.path.isdir(paths_dir):
        print(f"[ERROR] Paths directory does not exist: {paths_dir}")
        return source_functions

    # Find all JSON files in the paths directory
    json_files = sorted(Path(paths_dir).glob("*.json"))

    if not json_files:
        print(f"[WARNING] No path JSON files found in {paths_dir}")
        return source_functions

    print(f"\n[*] Loading path files from {paths_dir}")

    for json_file in json_files:
        # Function name is the filename without extension
        func_name = json_file.stem

        # Skip if this function wasn't found in the AST
        if func_name not in dependencies:
            print(f"  ⊘ Skipping {func_name} (not found in AST)")
            continue

        try:
            with open(json_file, 'r') as f:
                data = json.load(f)

            if data and 'paths' in data:
                # Create source function entry with dependencies
                source_func = {
                    "name": func_name,
                    "paths": data['paths'],
                    "required_functions": dependencies[func_name]
                }

                # Add signature if available
                if signatures and func_name in signatures:
                    source_func["signature"] = signatures[func_name]

                source_functions.append(source_func)

                deps_str = f" (deps: {', '.join(dependencies[func_name])})" if dependencies[func_name] else ""
                sig_str = f"\n    Signature: {signatures[func_name]}" if signatures and func_name in signatures else ""
                print(f"  ✓ Loaded {len(data['paths'])} path(s) for function: {func_name}{deps_str}{sig_str}")
            else:
                print(f"  ✗ No paths found in: {json_file.name}")

        except Exception as e:
            print(f"  ✗ Failed to load {json_file.name}: {e}")

    return source_functions


def main():
    """Main function to create source_functions.json with dependencies"""
    parser = argparse.ArgumentParser(
        description="Create source_functions.json with function dependency tracking from AST",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python scripts/create_source_functions_json_with_deps.py bst test/projects/bst tmp/paths tmp/ast/bst.json
  python scripts/create_source_functions_json_with_deps.py qsort test/projects/qsort tmp/paths tmp/ast/qsort.json
        """
    )

    parser.add_argument(
        'subject_name',
        help='Name of the subject (e.g., qsort, bst)'
    )

    parser.add_argument(
        'output_dir',
        help='Output directory where source_functions.json will be created'
    )

    parser.add_argument(
        'paths_dir',
        help='Directory containing path JSON files from CFG analysis'
    )

    parser.add_argument(
        'ast_file',
        help='AST JSON file generated by ast_generator.py'
    )

    parser.add_argument(
        '--verbose', '-v',
        action='store_true',
        help='Enable verbose output'
    )

    args = parser.parse_args()

    print("="*60)
    print("Source Functions JSON Creator (with Dependencies)")
    print("="*60)
    print(f"Subject:     {args.subject_name}")
    print(f"Output dir:  {args.output_dir}")
    print(f"Paths dir:   {args.paths_dir}")
    print(f"AST file:    {args.ast_file}")
    print("="*60)

    # Create output directory if it doesn't exist
    os.makedirs(args.output_dir, exist_ok=True)

    # Load and parse AST
    if not os.path.exists(args.ast_file):
        print(f"\n[ERROR] AST file not found: {args.ast_file}")
        print("[ERROR] Run the preprocessor first to generate AST files")
        return 1

    print(f"\n[*] Loading AST from {args.ast_file}...")
    try:
        with open(args.ast_file, 'r') as f:
            ast_data = json.load(f)
    except Exception as e:
        print(f"[ERROR] Failed to load AST file: {e}")
        return 1

    # Extract dependencies from AST
    print("[*] Extracting function dependencies from AST...")
    extractor = DependencyExtractor(ast_data)
    dependencies = extractor.extract_dependencies()

    if not dependencies:
        print("[WARNING] No functions found in AST")
        return 1

    print(f"[SUCCESS] Found {len(dependencies)} function(s) in AST")

    if args.verbose:
        print("\n[*] Function dependencies:")
        for func, deps in dependencies.items():
            if deps:
                print(f"  {func} → {{{', '.join(deps)}}}")
            else:
                print(f"  {func} → {{}}")

    # Extract function signatures from AST
    print("\n[*] Extracting function signatures from AST...")
    signatures = extract_all_function_signatures(ast_data)

    if signatures:
        print(f"[SUCCESS] Extracted {len(signatures)} function signature(s)")
        if args.verbose:
            print("\n[*] Function signatures:")
            for func_name, signature in sorted(signatures.items()):
                print(f"  {func_name}: {signature}")
    else:
        print("[WARNING] No function signatures extracted from AST")

    # Load paths and merge with dependencies and signatures
    source_functions = load_paths_and_merge_dependencies(args.paths_dir, dependencies, signatures)

    if not source_functions:
        print("\n[WARNING] No source functions with paths found")
        return 1

    # Create source_functions.json structure
    output_data = {
        "source_functions": source_functions
    }

    # Save to file
    output_file = os.path.join(args.output_dir, "source_functions.json")
    print(f"\n[*] Saving source_functions.json...")

    try:
        with open(output_file, 'w') as f:
            json.dump(output_data, f, indent=2)

        print(f"[SUCCESS] Created {output_file}")
        print(f"[INFO] Included {len(source_functions)} function(s):")

        for func in source_functions:
            num_paths = len(func.get('paths', []))
            deps = func.get('required_functions', [])
            signature = func.get('signature', 'N/A')
            deps_str = f" → {{{', '.join(deps)}}}" if deps else " → {{}}"
            print(f"  - {func['name']}: {num_paths} path(s){deps_str}")
            print(f"      Signature: {signature}")

        return 0

    except Exception as e:
        print(f"[ERROR] Failed to save {output_file}: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(main())