#!/usr/bin/env python3
"""
Extract function signatures from Tree-sitter AST JSON files

This module provides utilities to extract function signatures from AST JSON files
generated by ast_generator.py.
"""

import json
from typing import Dict, List, Optional, Any


def get_text_from_node(node: Dict[str, Any], source_bytes: bytes) -> str:
    """
    Extract text from a node using its byte positions.

    Args:
        node: AST node dictionary
        source_bytes: Source code as bytes

    Returns:
        Text content of the node
    """
    if 'text' in node:
        return node['text']

    start = node.get('start_byte', 0)
    end = node.get('end_byte', 0)

    if start >= 0 and end > start:
        try:
            return source_bytes[start:end].decode('utf-8')
        except (UnicodeDecodeError, IndexError):
            return ''

    return ''


def extract_return_type_and_declarator(node: Dict[str, Any], source_bytes: bytes) -> tuple:
    """
    Extract return type and declarator from function definition node.
    Handles pointer return types correctly.

    Args:
        node: function_definition AST node
        source_bytes: Source code as bytes

    Returns:
        Tuple of (return_type_string, declarator_node, pointer_count)
    """
    # The return type is typically the first child(ren) before the declarator
    children = node.get('children', [])
    if not children:
        return 'void', None, 0

    return_type_parts = []
    declarator = None
    pointer_count = 0

    for child in children:
        node_type = child.get('type', '')

        # Collect type specifiers before declarator
        if node_type in ['primitive_type', 'struct_specifier', 'type_identifier',
                        'sized_type_specifier', 'storage_class_specifier']:
            text = get_text_from_node(child, source_bytes)
            if text:
                return_type_parts.append(text)

        # Found the declarator
        elif 'declarator' in node_type:
            declarator = child
            # Count pointers in pointer_declarator
            if node_type == 'pointer_declarator':
                # Count '*' characters
                for grandchild in child.get('children', []):
                    if grandchild.get('type') == '*':
                        pointer_count += 1
            break

    return_type = ' '.join(return_type_parts) if return_type_parts else 'void'
    return return_type, declarator, pointer_count


def extract_function_name(declarator: Dict[str, Any], source_bytes: bytes) -> Optional[str]:
    """
    Extract function name from a declarator node.

    Args:
        declarator: declarator AST node
        source_bytes: Source code as bytes

    Returns:
        Function name or None
    """
    node_type = declarator.get('type', '')

    # Direct function declarator
    if node_type == 'function_declarator':
        children = declarator.get('children', [])
        if children:
            first_child = children[0]
            if first_child.get('type') == 'identifier':
                return get_text_from_node(first_child, source_bytes)

    # Pointer declarator wrapping function declarator
    elif node_type == 'pointer_declarator':
        children = declarator.get('children', [])
        for child in children:
            if child.get('type') == 'function_declarator':
                return extract_function_name(child, source_bytes)

    # Recursively search children
    children = declarator.get('children', [])
    for child in children:
        result = extract_function_name(child, source_bytes)
        if result:
            return result

    return None


def extract_parameters(declarator: Dict[str, Any], source_bytes: bytes) -> str:
    """
    Extract parameter list from a declarator node.

    Args:
        declarator: declarator AST node
        source_bytes: Source code as bytes

    Returns:
        Parameter list string (e.g., "int x, char* y")
    """
    def find_parameter_list(node):
        """Find parameter_list node recursively."""
        if node.get('type') == 'parameter_list':
            return node

        for child in node.get('children', []):
            result = find_parameter_list(child)
            if result:
                return result
        return None

    param_list = find_parameter_list(declarator)
    if not param_list:
        return '()'

    # Extract the full parameter list text
    param_text = get_text_from_node(param_list, source_bytes)
    return param_text if param_text else '()'


def extract_function_signature(func_def: Dict[str, Any], source_bytes: bytes) -> Optional[str]:
    """
    Extract complete function signature from function_definition node.

    Args:
        func_def: function_definition AST node
        source_bytes: Source code as bytes

    Returns:
        Complete function signature string or None
    """
    if func_def.get('type') != 'function_definition':
        return None

    # Extract return type and declarator
    return_type, declarator, pointer_count = extract_return_type_and_declarator(func_def, source_bytes)

    if not declarator:
        return None

    # Extract function name
    func_name = extract_function_name(declarator, source_bytes)
    if not func_name:
        return None

    # Extract parameters
    params = extract_parameters(declarator, source_bytes)

    # Construct signature with proper pointer syntax
    pointer_str = '*' * pointer_count
    if pointer_str:
        signature = f"{return_type}{pointer_str} {func_name}{params}"
    else:
        signature = f"{return_type} {func_name}{params}"

    # Clean up extra whitespace
    signature = ' '.join(signature.split())

    return signature


def extract_all_function_signatures(ast_data: Dict[str, Any]) -> Dict[str, str]:
    """
    Extract all function signatures from an AST JSON structure.

    Args:
        ast_data: Complete AST JSON data structure

    Returns:
        Dictionary mapping function names to their signatures
    """
    signatures = {}

    # Get source code if available
    source_bytes = b''
    if 'source_code' in ast_data:
        source_bytes = ast_data['source_code'].encode('utf-8')

    def traverse(node):
        """Recursively traverse AST to find function definitions."""
        if isinstance(node, dict):
            if node.get('type') == 'function_definition':
                signature = extract_function_signature(node, source_bytes)
                if signature:
                    # Extract function name from signature
                    # Simple heuristic: find the function name (word before '(')
                    import re
                    match = re.search(r'(\w+)\s*\(', signature)
                    if match:
                        func_name = match.group(1)
                        signatures[func_name] = signature

            # Traverse children
            if 'children' in node:
                for child in node['children']:
                    traverse(child)

    # Start traversal from root
    if 'root_node' in ast_data:
        traverse(ast_data['root_node'])

    return signatures


def load_ast_and_extract_signatures(ast_file_path: str) -> Dict[str, str]:
    """
    Load an AST JSON file and extract all function signatures.

    Args:
        ast_file_path: Path to AST JSON file

    Returns:
        Dictionary mapping function names to their signatures
    """
    try:
        with open(ast_file_path, 'r') as f:
            ast_data = json.load(f)

        return extract_all_function_signatures(ast_data)

    except Exception as e:
        print(f"Error loading AST file {ast_file_path}: {e}")
        return {}


def main():
    """Test the signature extraction."""
    import sys

    if len(sys.argv) < 2:
        print("Usage: python extract_function_signatures.py <ast_json_file>")
        sys.exit(1)

    ast_file = sys.argv[1]
    signatures = load_ast_and_extract_signatures(ast_file)

    print(f"Extracted {len(signatures)} function signatures from {ast_file}:")
    print("="*60)
    for func_name, signature in sorted(signatures.items()):
        print(f"{func_name}:")
        print(f"  {signature}")
        print()


if __name__ == "__main__":
    main()
